### ISSUE TITLE
Switch to actively maintained Fomantic-UI (backwards compatible)

### ISSUE THREAD

**Issue by lubber-de** [fossasia/open-event-theme#16]
Semantic UI has'nt been maintained since 2018, but the active community fork https://fomantic-ui.com already got 500 bugfixes and new features like calendar, slider, toast, etc. 

it is backward compatible, the current code should work as it is.

https://fomantic-ui.com
https://github.com/fomantic/fomantic-ui

**Comment by iamareebjamal** [comment]
Yes, we've planned to try it out and will soon comment if we need any help. Thanks a lot for reaching out :)

**Comment by iamareebjamal** [comment]
We tried fomantic UI here https://github.com/fossasia/open-event-frontend/pull/4538 but it caused modals (https://github.com/fomantic/Fomantic-UI/issues/1590) and nested popups to break  https://github.com/fossasia/open-event-frontend/issues/4730 and https://github.com/fossasia/open-event-frontend/issues/4735

So, we cherry-picked the fix for scroll lock from this PR https://github.com/fomantic/Fomantic-UI/pull/273 in https://github.com/fossasia/open-event-theme/commit/d2473e576765cdfa98b36eeb3d9ea3be07137cf8 and everything is working now.

- [x] Dimmer close on cross button
- [x] Dimmer is not repeated on interaction
- [x] Scroll lock doesn't happen
